name: Node CI Workflow
run-name: ${{ github.actor }} start the CI workflow
on:
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Compile TS file to JS file
        run: npm run build --if-present
      - name: Test the app
        run: npm test
      

